---
title: "Wild Git Collaboration Practice"
format: 
  html:
    code-fold: show
execute: 
  warning: false
  message: false
---


## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)
library(ggplot2)
library(tidyverse)

data(diamonds)

ggplot(data=diamonds, aes(x=carat, y = price)) + 
  geom_point() + 
  theme_bw()

```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"
library(ggplot2)
library(tidyverse)
data(diamonds)

ggplot(data=diamonds, aes(x= carat, y= price)) +
       geom_point()+
  theme_bw()
  

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}

carat_data = diamonds |>
  select(carat, cut, color, clarity, depth, table, price)


ggplot(data = diamonds, aes(x = cut, y = price)) +
  geom_boxplot() +
  theme_bw()

```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

